### DISCUSSION TITLE
Best Practice Improvements

### DISCUSSION THREAD

**Discussion by mnordhaus** [zetxek/adritian-free-hugo-theme#191] [Ideas]
While I on my own Website using the theme I figured some points that might help - utilize Best Practices:

### Better harness the template lookup order and especially use the baseof template
Hugo has a very powerful way using a Lookup Order for Templates. The theme does not use the baseof template at the moment.
It might also be helpful to use render hooks and content views
https://gohugo.io/templates/lookup-order/
https://gohugo.io/templates/base/
https://gohugo.io/templates/types/

### Do not use i18n for content - Cleary distinguish 
The theme has a lot of what I would consider Content within i18n files. From my point of view it would be better to move that into the Content folder (en / de / es / ...). Example:

```
## Homepage head title
- id: "head_title"
  translation: "Demo site for Adritian - a high performance hugo theme by Adrián Moreno"

- id: "head_description"
  translation: "This hugo theme (Adritian) is based on Bootstrap and has features that make it suitable for a personal site, a portfolio or other kind of Single Page Applications."
```

### Landingpage CMS friendly 
Put sections for a landingpage (like the Homepage, that is something to be generalized IMHO) in a page file like that:

```
sections:
  - template: showcase
     metafield1: matavalue1
     mefafield2: metavalue2
     ...
     metafieldN: metavalueN
     content:
      ... individual set of fields for the section type
  - template: about
     metafield1: matavalue1
     mefafield2: metavalue2
     ...
     metafieldN: metavalueN
     content:
      ... individual set of fields for the section type
```

### Bootstrap / Sass Best Practices
-> https://www.hugolify.io/docs/getting-started/best-practices/

### Removing the Example Content out of the theme and bundle it with the "all batteries included asset" later on
It feels a little bit odd to have the example content available in the theme (including assets and images not within the example folder) when using it as a module. The content is obscure and might accidentally interfere with content of the production website.

On the other hand it is good to have examples available. I guess a good idea is to treat that the same as the bootstrap dependencies.
