### DISCUSSION TITLE
Ideas for a typographically sound blog layout

### DISCUSSION THREAD

**Discussion by maxwelljens** [zetxek/adritian-free-hugo-theme#221] [Ideas]
I have developed a `custom.css` file for [my website](https://maxwelljensen.eu/blog/) to make the blog layout a lot easier to read, since the current iteration of the theme's defaults are not optimised for long-form reading. While I did make it for my own use – of course – I think the changes I made would make for reasonable defaults on the theme too. Some guidelines I followed when making the changes:

- Keeping the characters per line (CPL) count below 80, since [that's generally the human optimal](https://baymard.com/blog/line-length-readability). 
- Making use of `rem` or `em` where appropriate, so that the changes work with any font (the examples below use Inter).
- Using theme colour variables instead of specifying individual colours. As a side note: theme does not use variables in all elements, leading to occasionally inconsistent behaviour, particularly between light and dark themes.

It's still a work in progress. I plan on changing more of the layout later, as there's still a few issues there and there, but I think this would make for a very good start towards prettier defaults.

Desktop appearance:

![image](https://github.com/user-attachments/assets/ef5eaa97-18fe-4d8b-b30f-f1b8376530a5)
![image](https://github.com/user-attachments/assets/9d6ee046-15fd-4825-a28d-051663b1a302)
![image](https://github.com/user-attachments/assets/f6384f23-29f2-42ea-8f28-c883b9b65598)
![image](https://github.com/user-attachments/assets/1bd7b1a3-d27b-4064-886e-5677ed48579d)

Mobile appearance:

![image](https://github.com/user-attachments/assets/730f1bb5-6e5a-4961-bc4a-3ce529673a22)
![image](https://github.com/user-attachments/assets/f9aa4925-4dda-4e2c-9759-702c12d106d7)

The `assets/css/custom.css` file:

```scss
.posts-list article.summary p,
.posts-list article.summary ul,
#blog-single p,
#blog-single ul {
  font-size: 1.1rem;
  line-height: 1.75em;
  padding-bottom: 0.5em;
}

.posts-list, #blog-single {
  max-width: 46rem;
}

/* Makes underlined links consistent across dark and light theme */
.posts-list p a, #blog-single p a {
  border-bottom: 1px solid var(--bs-body-color);
}

/* Include unordered lists too, since they are treated differently by default */
.posts-list ul a, #blog-single ul a {
  border-bottom: 1px solid var(--bs-body-color);
  color: var(--bs-body-color);
  font-weight: 600;
}

/* Centre the blog article */
#blog-single {
  margin: 0 auto;
}

/* Make code blocks prettier */
pre, textarea {
  padding: 20px;
}

/* Make inline code text stand out more from regular body text */
p code {
  border-color: var(--bs-code-color);
  border-style: solid;
  border-radius: 4px;
  border-width: 1px;
  padding: 0.25rem;
}

/* Make the tags stick out less, but still doesn't look ideal.
*  Different approach might be needed. */
ul.tags li {
  background-color: initial;
  border-color: var(--bs-gray-500);
  border-style: solid;
  border-radius: 4px;
  border-width: 1px;
}

ul.tags li::before {
  background-color: var(--bs-gray-500) !important;
}

[data-bs-theme="dark"] ul.tags li {
  background-color: initial;
  border-color: var(--bs-body-color);
}

[data-bs-theme="dark"] .blog .blog-sidebar .sidebar-section ul li a {
  color: var(--bs-body-color) !important;
}

/* Squeeze more text onto the screen on mobile devices */
@media (max-width: 520px) {
  .posts-list article.summary p,
  .posts-list article.summary ul,
  #blog-single p,
  #blog-single ul {
    font-size: 13px;
  }
}
```
