### ISSUE TITLE
[FR] picture alignment in about section

### ISSUE THREAD

**Issue by klangborste** [zetxek/adritian-free-hugo-theme#189]
Hello @zetxek, what you think about an optional switch to align the picture from the "about" section to the first section with the introduction?
![Image](https://github.com/user-attachments/assets/a6b0af04-8afe-422e-9cc2-594cd05b9130)

BR

**Comment by zetxek** [comment]
The idea would be to be able to have the picture in the right, instead of on the left?
Should be fairly simple :), and customizable via a parameter...

**Comment by klangborste** [comment]
That's was not the initial idea, but this is also something would be nice to have in the theme.
I mean more to adjust the picture to be more adjusted near to the text.

**Comment by mnordhaus** [comment]
I am currently rethinking how the homepage works in general and turn it into a landinpage template that can be used otherwise too. During that I will likely create new sections or blocks (a better name is welcome, since both are Hugo concepts actually).

**Comment by zetxek** [comment]
I would think of them as "components". As they're basically HTML and CSS to render some content in different parts.

The term section comes from the original theme I forked, but didn't give it too much thought as we didn't change it much (yet).

**Comment by zetxek** [comment]
Ok @klangborste it has taken me a while - I had almost forgotten!

But with the new content styles of the theme, that uses `shortcodes` in the `markdown` files for the setup... this was quite a breeze :) 

I have implemented it in https://github.com/zetxek/adritian-free-hugo-theme/pull/312 - you can see the screenshot with the example. I'll release it in some minutes under a new theme version.

I hope it's still useful to you!

**Comment by klangborste** [comment]
Hey @zetxek, thanks a lot for come back to this issue.
I appreciate your effort and it took ages to answer.
The vertical alignment was not really my original request, it is about the horizontal alignment.
**Before it was looking like the initial picture:**
<img width="3839" height="1195" alt="Image" src="https://github.com/user-attachments/assets/8562bbc3-c117-44f2-8a5c-2c1344b4d721" />
**I wanted that it looks like that now:**
<img width="3839" height="1267" alt="Image" src="https://github.com/user-attachments/assets/a7d5fe5e-64b6-4928-bc5e-2aa7424e7dfd" />
This was added to get it work:
**repo-root\assets\css\custom.css**
```css
.header .navbar-brand img {
    max-height: 90px !important;
}

/* Align profile picture with other content while keeping it on the left */
@media (min-width: 768px) {
    .about__profile-picture {
        margin-left: 120px !important;
        margin-right: 0 !important;
    }
    
    /* Ensure the about section uses flexbox to keep content side by side */
    .about .row {
        display: flex !important;
        align-items: flex-start !important;
    }
    
    /* Make sure the text column takes remaining space */
    .about__profile-picture + div {
        flex: 1 !important;
        margin-left: 40px !important;
    }
}

/* Ensure proper alignment */
.about__profile-picture img {
    display: block !important;
}
````
